// Writes deployments/<network>.json and regenerates frontend/contract-config.js,
// which gives the web page the contract ABI and every deployed address.
const fs = require("fs");
const path = require("path");

const ROOT = path.join(__dirname, "..");
const DEPLOYMENTS_DIR = path.join(ROOT, "deployments");
const FRONTEND_CONFIG = path.join(ROOT, "frontend", "contract-config.js");

// Public settings the browser uses. Keep API keys out of here: this file is served to every visitor.
const NETWORKS = {
  monadTestnet: {
    label: "Monad Testnet",
    chainId: 10143,
    rpcUrl: "https://testnet-rpc.monad.xyz",
    currency: "MON",
    explorer: "https://testnet.monadvision.com",
    faucet: "https://faucet.monad.xyz",
  },
  localhost: {
    label: "Hardhat Local",
    chainId: 31337,
    rpcUrl: "http://127.0.0.1:8545",
    currency: "ETH",
    explorer: "",
    faucet: "",
  },
};

function saveDeployment(hre, contractName, record) {
  const network = hre.network.name;
  if (!NETWORKS[network]) {
    console.log(`(Not saved: the "${network}" network disappears when this command ends. Use --network localhost or monadTestnet.)`);
    return;
  }
  fs.mkdirSync(DEPLOYMENTS_DIR, { recursive: true });
  const file = path.join(DEPLOYMENTS_DIR, `${network}.json`);
  fs.writeFileSync(file, JSON.stringify({ contractName, network, ...record }, null, 2) + "\n");
  console.log(`Saved ${path.relative(ROOT, file)}`);
  writeFrontendConfig(hre, contractName);
}

function writeFrontendConfig(hre, contractName) {
  const { abi } = hre.artifacts.readArtifactSync(contractName);
  const deployments = {};
  for (const [network, settings] of Object.entries(NETWORKS)) {
    const file = path.join(DEPLOYMENTS_DIR, `${network}.json`);
    if (!fs.existsSync(file)) continue;
    const record = JSON.parse(fs.readFileSync(file, "utf8"));
    deployments[network] = { ...settings, address: record.address, deployedAt: record.deployedAt };
  }
  const config = { contractName, abi, deployments };
  const js =
    "// Auto-generated by scripts/deploy.js - do not edit by hand.\n" +
    `window.CONTRACT_CONFIG = ${JSON.stringify(config, null, 2)};\n`;
  fs.writeFileSync(FRONTEND_CONFIG, js);
  console.log(`Updated ${path.relative(ROOT, FRONTEND_CONFIG)}`);
}

module.exports = { NETWORKS, saveDeployment, writeFrontendConfig };
